name: Main

on:
  push:
  pull_request:
  issues:
  issue_comment:
  workflow_dispatch:

jobs:
  main:
    uses: codeforlife-education/codeforlife-workspace/.github/workflows/frontend.yaml@main
    secrets: inherit
    permissions:
      id-token: write
